org: kamilmateusiak
service: serverless-http-api-typescript
app: recru-task
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  getPayments:
    handler: handler.getPayments
    events:
      - httpApi:
          path: /get-payments
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline