service: serverless-http-api-typescript
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  payments:
    handler: handler.payments
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript